version: "3.3"

volumes:
  dbdata:

configs:
  nginx_conf:
    file: ./schedules_web/nginx.conf

networks:
  front:
  back:

services:
  api:
    image: registry.srct.gmu.edu/srct/schedules/api:v0.1.0
    networks:
      back:
    environment:
      RAILS_LOG_TO_STDOUT: "yes"
    command: "rails s"

  web:
    image: registry.srct.gmu.edu/srct/schedules/web:v0.1.0
    networks:
      front:
      back:
    ports:
      - 8085:80
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf

