FROM ruby:2.5

# Copy the project files to /api
COPY . /api

# Tell Docker to run all commands in /api
WORKDIR /api

# Install project dependencies
RUN bundle install

# Perform database migrations
RUN rails db:migrate

# Load the database from Patriot Web
RUN rails db:seed
