FROM starefossen/ruby-node:latest

RUN mkdir /schedules
WORKDIR /schedules
ADD . /schedules

EXPOSE 3000

ENV RAILS_ENV development

RUN bundle install
RUN yarn install
RUN rails db:migrate
RUN rails db:seed
RUN rails runner db/load_course_ratings.rb

CMD ["./start.sh"]
